@echo off
echo Stopping any running Metro bundler...
taskkill /F /IM node.exe 2>nul
echo Clearing Metro cache...
if exist node_modules\.cache rmdir /s /q node_modules\.cache
echo Starting development server...
npx expo start --clear 